name: "Update repo and (re-)deploy all datamesh jobs"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    name: "Update repo in databricks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy bundle
        run: databricks repos update /Repos/johan.gustaf.eriksson@spv.no/databricks-dataops-course --branch main
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST }}

  run:
    name: "Run one time job to update all jobs in datamesh"
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Run bundle
        run: databricks jobs submit --json @deploy/deploy_job.json
        working-directory: .
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST }}
